[build]
  command = "npx @11ty/eleventy"
  publish = "_site"              

[functions]
  directory = ".netlify/functions" 

[dev]
  command = "npx @11ty/eleventy --serve" 
  port = 8888                            
  targetPort = 8080                      
